### ISSUE TITLE
How to calculate Accuracy, Recall and F-Score using your project.

### ISSUE THREAD

**Issue by guilhermenoronha** [jidasheng/bi-lstm-crf#12]
Hello, it's me again.

I trained my model and I want to calculate its performance using the F-Score metric. How could I calculate it using your project? Thanks in advance. :)

**Comment by jidasheng** [comment]
You have the sentence, this project give you the predicted tags, so you can use the sklearn F-Score metric.

**Comment by guilhermenoronha** [comment]
Indeed. Thx for the support.
