### ISSUE TITLE
question about application of prediction

### ISSUE THREAD

**Issue by marcusau** [jidasheng/bi-lstm-crf#5]
After completion of my model training, i wanna test the result and got problem of that.

my code: 
    from bi_lstm_crf.app import WordsTagger

    model_dir= './model'
    model = WordsTagger(model_dir=model_dir)

    sentence='國家外匯管理局公佈，截至2019年11月末，中國外匯儲備規模為30,956億美元'

    tags, sequences = model([sentence])  # CHAR-based model
    print(tags)

    print(sequences)

The result :

    Traceback (most recent call last):
      File "/Users/marcusau/PycharmProjects/jidasheng/test.py", line 10, in <module>
        tags, sequences = model([sentence])  # CHAR-based model
    ValueError: not enough values to unpack (expected 2, got 1)

Note: i use char-based model training

**Comment by jidasheng** [comment]
update the package and try again.

**Comment by marcusau** [comment]
noted , do it now

**Comment by marcusau** [comment]
perfect now

    print(sequences[0])
    ['國家外匯管理局', '公佈', '，', '截至', '2019年', '11月', '末', '，', '中國外匯儲備', '規模', '為', '30,95', '6', '億', '美元']

**Comment by jidasheng** [comment]
well done.
