### ISSUE TITLE
if for Part of the speech, feasible?

### ISSUE THREAD

**Issue by marcusau** [jidasheng/bi-lstm-crf#6]
for example.

jieba pos tags: 'nr'='人名',=, 'nt'='機構名' ,'w'=符號

**Comment by jidasheng** [comment]
Of course. All sequence labeling tasks are possible. You can even combine word segmentation, pos tagging and ner into a single model.

B-PERSON, I-PERSON, B-N, I-N, ...
B/I for entity/word boundary, PERSON/N for entity/pos type.

**Comment by marcusau** [comment]
that means :
喬布斯/nr  , 蘋果公司/nt,  提出/v  ----->  「'B-NR' , 'I-NR' ,  'I-NR' , 'B-NT' , 'I-NT' , 'I-NT' , ''I-NT , 'I-NT' , 'B-V' , 'I-V' ]

correct format??

**Comment by jidasheng** [comment]
exactly

**Comment by marcusau** [comment]
好，我現在玩
