### ISSUE TITLE
您好，请问您用这个代码跑过数据集吗？

### ISSUE THREAD

**Issue by Daniel19960601** [jidasheng/bi-lstm-crf#7]
您好，请问您用这个代码跑过数据集吗？我在微软公开数据集上F1只能到60%+，怎么都提升不上来。

**Comment by jidasheng** [comment]
在私有数据集上是跑过的。你能把你的问题描述得更清楚一点吗？比如数据集的下载地址，具体哪一个任务，你问题的截图等。

**Comment by Daniel19960601** [comment]
> 在私有数据集上是跑过的。你能把你的问题描述得更清楚一点吗？比如数据集的下载地址，具体哪一个任务，你问题的截图等。

不好意思 这么久才回复您。
我使用的是msra的ner数据集(http://file.hankcs.com/corpus/msra_ner.zip)，代码没有任何问题，只是跑完之后，用conlleval这个工具评估F1只有60%+，怎么也提升不上来。甚至根据《Neural Architectures for Named Entity Recognition》这篇文章的参数调整，得到的结果非常不可思议。
劳烦指点。

**Comment by jidasheng** [comment]
有训练结果和评测结果的截图吗？最近身边都没用电脑，无法去复现你的问题。只能看看能不能从你的中间结果中定位到问题。

**Comment by Daniel19960601** [comment]
> 有训练结果和评测结果的截图吗？最近身边都没用电脑，无法去复现你的问题。只能看看能不能从你的中间结果中定位到问题。

感谢您的回复。
我最近也没有gpu，用cpu跑了20个epoch，下面分别是训练的curve和评测截图（图中F1只有20多，因为epoch太少了，训练足量epoch(loss不再下降时(大概是1.+)可以达到60多)）
![image](https://user-images.githubusercontent.com/20382469/74236174-a4052100-4d0b-11ea-8880-496177f0cd62.png)
![image](https://user-images.githubusercontent.com/20382469/74236197-ae271f80-4d0b-11ea-853c-10f63a16fd8f.png)
看来其他的issue，还想再向您确认一下，这样的tag（如下图）是没错的把？
![image](https://user-images.githubusercontent.com/20382469/74236257-cc8d1b00-4d0b-11ea-9b8b-cc229a7bf279.png)

**Comment by jidasheng** [comment]
我们这个包是兼容这种tag的，但是你所用的那个评估包好像是不兼容的，你最好把BMES改为BIES再试试。
另外，你可以把评估的输入发出来看看，也就人眼看看预测结果，看看能不能发现问题

**Comment by Daniel19960601** [comment]
> 我们这个包是兼容这种tag的，但是你所用的那个评估包好像是不兼容的，你最好把BMES改为BIES再试试。
> 另外，你可以把评估的输入发出来看看，也就人眼看看预测结果，看看能不能发现问题

我之前都是用的是BIO标签跑的

预测结果：
链接：https://pan.baidu.com/s/10SJ2s9dtMra49SelkURoWA 
提取码：leum
(第二列是正确的tag，第三列是预测的tag)
(太大了，所以用了网盘)

**Comment by jidasheng** [comment]
这个没看出问题，只是结果比较糟糕，应该是没有完全训练完的结果吧？
如果训练完全了，可以提供一个结果出来，只要贴出几句话的结果就行了，不用整个文件。
另外，等我方面的时候，我可以重现一下这个训练。不过受疫情影响，可能会等很久了。

**Comment by Daniel19960601** [comment]
> 这个没看出问题，只是结果比较糟糕，应该是没有完全训练完的结果吧？
> 如果训练完全了，可以提供一个结果出来，只要贴出几句话的结果就行了，不用整个文件。
> 另外，等我方面的时候，我可以重现一下这个训练。不过受疫情影响，可能会等很久了。

嘿嘿，好的，谢谢你。
过两天我租用个服务器跑一下给你发。
早点休息，晚安惹~

**Comment by Daniel19960601** [comment]
> 这个没看出问题，只是结果比较糟糕，应该是没有完全训练完的结果吧？
> 如果训练完全了，可以提供一个结果出来，只要贴出几句话的结果就行了，不用整个文件。
> 另外，等我方面的时候，我可以重现一下这个训练。不过受疫情影响，可能会等很久了。
嗨，最近还好吗？
我换成BIO标签跑了一下，除了设置了保存最佳模型（--save_best_val_model），epoch_num设置的200，但是大概70多val loss就不下降了，所以早停了， 其他用的都是代码里默认的参数。
下面是一些结果：
![image](https://user-images.githubusercontent.com/20382469/74666511-96a0d880-51dc-11ea-87a7-429e8143ef4f.png)
👆训练和验证曲线
![image](https://user-images.githubusercontent.com/20382469/74666556-addfc600-51dc-11ea-992b-bb7663845338.png)
👆conlleval测试结果
👇接下来是一些测试结果（第二列是正确的标签，第三列是预测标签）
中 B-ORG B-ORG
共 I-ORG I-ORG
中 I-ORG I-ORG
央 I-ORG I-ORG
致 O O
中 B-ORG B-LOC
国 I-ORG I-LOC
致 I-ORG I-ORG
公 I-ORG I-ORG
党 I-ORG I-ORG
十 I-ORG O
一 I-ORG O
大 I-ORG O
的 O O
贺 O O
词 O O
---------------------------------------------
在 O O
中 B-ORG B-ORG
国 I-ORG I-ORG
致 I-ORG I-ORG
公 I-ORG I-ORG
党 I-ORG I-ORG
第 I-ORG O
十 I-ORG O
一 I-ORG O
次 I-ORG O
全 I-ORG O
国 I-ORG O
代 I-ORG O
表 I-ORG O
大 I-ORG O
会 I-ORG O
隆 O O
重 O O
召 O O
开 O O
之 O O
际 O O
， O O
中 B-ORG B-ORG
国 I-ORG I-ORG
共 I-ORG I-ORG
产 I-ORG I-ORG
党 I-ORG I-ORG
中 I-ORG I-ORG
央 I-ORG I-ORG
委 I-ORG I-ORG
员 I-ORG O
会 I-ORG I-ORG
谨 O O
向 O O
大 O O
会 O O
表 O O
示 O O
热 O O
烈 O O
的 O O
祝 O O
贺 O O
， O O
向 O O
致 B-ORG O
公 I-ORG O
党 I-ORG O
的 O O
同 O O
志 O O
们 O O
---------------------------------------------
高 O O
举 O O
爱 O O
国 O O
主 O O
义 O O
和 O O
社 O O
会 O O
主 O O
义 O O
两 O O
面 O O
旗 O O
帜 O O
， O O
团 O O
结 O O
全 O O
体 O O
成 O O
员 O O
以 O O
及 O O
所 O O
联 O O
系 O O
的 O O
归 O O
侨 O O
、 O O
侨 O O
眷 O O
， O O
发 O O
扬 O O
爱 O O
国 O O
革 O O
命 O O
的 O O
光 O O
荣 O O
传 O O
统 O O
， O O
为 O O
统 O O
一 O O
祖 O O
国 O O
、 O O
振 O O
兴 O O
中 B-LOC O
华 I-LOC O
而 O O
努 O O
力 O O
奋 O O
斗 O O
； O O
---------------------------------------------
致 B-ORG O
公 I-ORG B-ORG
党 I-ORG B-ORG
中 I-ORG I-ORG
央 I-ORG I-ORG
领 O O
导 O O
人 O O
多 O O
次 O O
参 O O
加 O O
中 B-ORG B-ORG
共 I-ORG I-ORG
中 I-ORG I-ORG
央 I-ORG I-ORG
和 O O
国 B-ORG B-ORG
务 I-ORG I-ORG
院 I-ORG I-ORG
举 O O
行 O O
的 O O
民 O O
主 O O
党 O O
派 O O
人 O O
士 O O
座 O O
谈 O O
会 O O
、 O O
协 O B-ORG
商 O I-ORG
会 O I-ORG
， O O
参 O O
与 O O
国 O O
家 O O
大 O O
政 O O
方 O O
针 O O
的 O O
协 O O
商 O O
， O O
认 O O
真 O O
履 O O
行 O O
参 O O
政 O O
议 O O
政 O O
、 O O
民 O O
主 O O
监 O O
督 O O
职 O O
能 O O
； O O
---------------------------------------------
广 O B-ORG
大 O O
成 O O
员 O O
在 O O
做 O O
好 O O
本 O O
职 O O
工 O O
作 O O
的 O O
同 O O
时 O O
， O O
把 O O
科 O O
技 O O
扶 O O
贫 O O
、 O O
智 O B-ORG
力 O O
支 O O
边 O O
作 O O
为 O O
为 O O
社 O O
会 O O
主 O O
义 O O
建 O O
设 O O
服 O O
务 O O
的 O O
一 O O
项 O O
重 O O
要 O O
工 O O
作 O O
， O O
不 O O
断 O O
开 O O
拓 O O
进 O O
取 O O
， O O
取 O O
得 O O
了 O O
可 O O
喜 O O
的 O O
成 O O
绩 O O
， O O
为 O O
促 O O
进 O O
社 O O
会 O O
主 O O
义 O O
物 O O
质 O O
文 O O
明 O O
和 O O
精 O O
神 O O
文 O O
明 O O
建 O O
设 O O
作 O O
出 O O
了 O O
积 O O
极 O O
贡 O O
献 O O
； O O
---------------------------------------------
在 O O
此 O O
， O O
中 B-ORG B-LOC
共 I-ORG I-LOC
中 I-ORG O
央 I-ORG O
谨 O O
向 O O
致 B-ORG O
公 I-ORG B-ORG
党 I-ORG I-ORG
中 I-ORG I-ORG
央 I-ORG I-ORG
以 O O
及 O O
全 O O
体 O O
成 O O
员 O O
致 O O
以 O O
崇 O O
高 O O
的 O O
敬 O O
意 O O
！ O O
---------------------------------------------
大 O O
会 O O
高 O O
举 O O
邓 B-PER B-PER
小 I-PER I-PER
平 I-PER I-PER
理 O O
论 O O
伟 O O
大 O O
旗 O O
帜 O O
， O O
回 O O
顾 O O
一 O O
个 O O
世 O O
纪 O O
以 O O
来 O O
中 B-LOC B-LOC
国 I-LOC I-LOC
人 O O
民 O O
的 O O
奋 O O
斗 O O
历 O O
史 O O
， O O
展 O O
望 O O
下 O O
个 O O
世 O O
纪 O O
５ O O
０ O O
年 O O
的 O O
发 O O
展 O O
前 O O
景 O O
， O O
认 O O
真 O O
总 O O
结 O O
了 O O
中 B-ORG B-LOC
共 I-ORG O
十 O O
一 O O
届 O O
三 O O
中 O O
全 O O
会 O O
以 O O
来 O O
特 O O
别 O O
是 O O
十 B-ORG O
四 I-ORG O
大 I-ORG O
以 O O
来 O O
的 O O
实 O O
践 O O
经 O O
验 O O
， O O
对 O O
中 B-LOC B-LOC
国 I-LOC I-LOC
改 O O
革 O O
开 O O
放 O O
和 O O
社 O O
会 O O
主 O O
义 O O
现 O O
代 O O
化 O O
建 O O
设 O O
跨 O O
世 O O
纪 O O
的 O O
发 O O
展 O O
作 O O
出 O O
了 O O
全 O O
面 O O
部 O O
署 O O
。 O O
---------------------------------------------
我 O O
们 O O
热 O O
诚 O O
希 O O
望 O I-ORG
致 B-ORG I-ORG
公 I-ORG I-ORG
党 I-ORG O
在 O O
今 O O
后 O O
的 O O
工 O O
作 O O
中 O O
， O O
充 O O
分 O O
发 O O
挥 O O
与 O O
海 O O
外 O O
联 O O
系 O O
广 O O
泛 O O
的 O O
优 O O
势 O O
， O O
多 O O
渠 O O
道 O O
、 O O
多 O O
层 O O
次 O O
、 O O
多 O O
形 O O
式 O O
地 O O
开 O O
展 O O
海 O O
外 O O
联 O O
络 O O
工 O O
作 O O
， O O
积 O O
极 O O
宣 O O
传 O O
邓 B-PER B-PER
小 I-PER I-PER
平 I-PER I-PER
“ O O
一 O O
国 O O
两 O O
制 O O
” O O
的 O O
科 O O
学 O O
构 O O
想 O O
和 O O
江 B-PER B-PER
泽 I-PER I-PER
民 I-PER I-PER
同 O O
志 O O
关 O O
于 O O
台 B-LOC B-LOC
湾 I-LOC I-LOC
问 O O
题 O O
的 O O
八 O O
项 O O
主 O O
张 O O
， O O
为 O O
保 O O
持 O O
香 B-LOC B-LOC
港 I-LOC I-LOC
的 O O
繁 O O
荣 O O
稳 O O
定 O O
， O O
为 O O
澳 B-LOC B-LOC
门 I-LOC I-LOC
的 O O
顺 O O
利 O O
回 O O
归 O O
和 O O
促 O O
进 O O
祖 O O
国 O O
完 O O
全 O O
统 O O
一 O O
作 O O
出 O O
新 O O
的 O O
更 O O
大 O O
的 O O
贡 O O
献 O O
。 O O
---------------------------------------------
１ O O
９ O O
９ O O
７ O O
年 O O
１ O O
月 O O
１ O O
９ O O
日 O O
是 O O
谢 B-PER O
子 I-PER I-PER
长 I-PER O
同 O O
志 O O
诞 O O
辰 O O
１ O O
０ O O
０ O O
周 O O
年 O O
。 O O
---------------------------------------------
在 O O
谢 B-PER O
子 I-PER O
长 I-PER O
百 O O
年 O O
诞 O O
辰 O O
纪 O O
念 O O
座 O O
谈 O O
会 O O
上 O O
的 O O
讲 O O
话 O O
（ O O
一 O O
九 O O
九 O O
七 O O
年 O O
一 O O
月 O O
二 O O
十 O O
日 O O
） O O
---------------------------------------------
谢 B-PER O
子 I-PER I-PER
长 I-PER O
同 O O
志 O O
是 O O
西 B-ORG B-LOC
北 I-ORG I-LOC
红 I-ORG I-ORG
军 I-ORG I-LOC
和 O O
西 B-LOC B-LOC
北 I-LOC I-LOC
革 I-LOC O
命 I-LOC O
根 I-LOC O
据 I-LOC O
地 I-LOC O
创 O O
始 O O
人 O O
之 O O
一 O O
。 O O
---------------------------------------------

有空帮看看哈~
（觉得你这个代码特别好，除了crf部分都看懂了，不知道结果为啥提不上来呢，好上心）
btw：我也跑了一下人民日报的数据，最后的F值和这个msra的数据差不多（参数同上）
![image](https://user-images.githubusercontent.com/20382469/74667560-707c3800-51de-11ea-87a4-d7992889e705.png)
👆人民日报数据评测结果

**Comment by jidasheng** [comment]
信息不全，不大好定位，如果方便，把全套代码和数据给我看看，特别是预处理之后的数据。

**Comment by Daniel19960601** [comment]
> 信息不全，不大好定位，如果方便，把全套代码和数据给我看看，特别是预处理之后的数据。

您真是太好惹~
全套代码和数据（42.45M，有点大）：
链接：https://pan.baidu.com/s/1hJBmGZLVb1aqojh8B82QnQ 
提取码：gygn 

您如果方便可以通过以下任何方式指教：
Email：773654915@qq.com
QQ/WeChat：773654915

**Comment by jidasheng** [comment]
我代码里有个问题，在viterbi解码部分，不影响训练，只影响预测，已修复并更新。你可以直接更新代码并测试一下你之前训练好的模型。我估计这个是主要问题。

另外，要提高你目前的算法表现，还可以尝试一下：
1）微软数据集你有些句子长度是超过100的，这个库默认句子长度是100，超过100会被截断，可能会影响训练。针对NER这个特殊情况，我认为可以将长句拆分成断句，比如以“，；”等为间隔，将长句再次拆分成断句，可以有效降低句子长度；
2）可以尝试其他的学习率。

最后，感谢帮助发现问题！

**Comment by jidasheng** [comment]
已解决
