### ISSUE TITLE
你好，请问CRF model里面的Mask是做什么用的？要怎么制作它呢？

### ISSUE THREAD

**Issue by Gs-Zhang** [jidasheng/bi-lstm-crf#8]

**Comment by Gs-Zhang** [comment]
根据我的理解，mask把输入的序列转化为pad和非pad的序列，但是不知道这样理解的对不对。

**Comment by Gs-Zhang** [comment]
因为bert的输出会有一个分词的过程，有可能一个词会被分成两个词，导致最后的标注和原来的序列长度不匹配。我自己的做法是在bert的输出进行处理，将分的词再合成一个词，保证输入输出的序列长度一致。

**Comment by jidasheng** [comment]
mask就是区分padding（对应0）和非padding（对应1）部分，只是个flag，在计算loss的时候要忽略padding部分产生的loss值。
BERT的中文是不分词的吧，是基于字的。

**Comment by jidasheng** [comment]
mask的制作，可以参考model/model.py文件：masks = sentences.gt(0)

**Comment by Gs-Zhang** [comment]
因为目前在尝试的数据集是英文的，自己之前测试的时候发现经常出现序列长度发生变化。中文这边后续也会尝试。谢谢你的解答和代码的开源。


 
---原始邮件---
发件人: "jidasheng"<notifications@github.com&gt;
发送时间: 2020年7月3日 16:22:43
收件人: "jidasheng/bi-lstm-crf"<bi-lstm-crf@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Gs-Zhang"<3022379889@qq.com&gt;;
主题: Re: [jidasheng/bi-lstm-crf] 你好，请问CRF model里面的Mask是做什么用的？要怎么制作它呢？ (#8)




 
mask就是区分padding（对应0）和非padding（对应1）部分，只是个flag，在计算loss的时候要忽略padding部分产生的loss值。
 BERT的中文是不分词的吧，是基于字的。
