### ISSUE TITLE
Error: Corpus_dir/vocab.json not found

### ISSUE THREAD

**Issue by Crowts** [jidasheng/bi-lstm-crf#9]
Hi @jidasheng 

I have been trying to run your implementation of the BiLSTM-CRF a couple of times but I keep getting an error. 
On my terminal I executed 
**>$ python -m bi_lstm_crf corpus_dir --model_dir "model xxx"** 

and got the following error (See attached image below for full details)
 **ValueError: "corpus_dir/vocab.json" file does not exist**

I've also tried **>$ python3 -m bi_lstm_crf corpus_dir --model_dir "model xxx"** but the same error persists.
I have not modified anything in the code and when I check inside "sample_corpus" the file "vocab.json" is there. 

I am new to BiLSTM-CRF code but I have read the paper [2] and a few others on NER using BiLSTM-CRF. Is there something wrong that I'm doing? Please advise. Thanks!

<img width="917" alt="Screenshot 2020-08-13 at 15 01 45" src="https://user-images.githubusercontent.com/36067020/90140520-284b6600-dd7a-11ea-8196-ecadb31277ef.png">

**Comment by Crowts** [comment]
Resolved

**Comment by FloraYRG** [comment]
Could I ask how you solved this problem?
